name: reviewdog
on: [pull_request, push]
jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      run: |
        touch .trufflehogignore
    - uses: UnicornGlobal/trufflehog-actions-scan@master
      with:
        branch: ${{ github.head_ref }}
#    - uses: actions/checkout@v2
#    - name: detect-secrets
#      uses: reviewdog/action-detect-secrets@master
#      with:
#        reporter: github-pr-review # Change reporter.
